services:
  api:
    image: <DOCKER_HUB_KULLANICI_ADIN>/myweb-docker-api:latest
    container_name: myweb-api
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  web:
    image: <DOCKER_HUB_KULLANICI_ADIN>/myweb-docker-web:latest
    container_name: myweb-web
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
