version: "3.9"

services:
  web:
    build: .
    container_name: myweb-container
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mymongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mymongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:

