name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: infra/docker/api.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myweb-docker-api:latest

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: infra/docker/web.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myweb-docker-web:latest
