name: Build and Deploy Full App (React +Express)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/myweb-docker
  TAG: latest

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file : ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

  deploy:
    name: Pull & Restart Container (Self-hosted)
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Docker login (gerekirse)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull & Restart
        run: |
          set -e
          CONTAINER_NAME=myweb
          IMAGE="${{ env.IMAGE }}:${{ env.TAG }}"

          echo "Pulling $IMAGE ..."
          docker pull "$IMAGE"

          echo "Stopping & removing old container if exists ..."
          docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

          echo "Starting new container ..."
          docker run -d \
            --name "$CONTAINER_NAME" \
            --restart unless-stopped \
            -p 80:3000 \
            "$IMAGE"

          echo "✅ Deployed $IMAGE as $CONTAINER_NAME"
