name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show workspace (debug)
        run: |
          pwd
          echo "--- ls -la (root) ---"
          ls -la
          echo "--- find level 2 ---"
          find . -maxdepth 2 -type d -print
          echo "--- .dockerignore ---"
          cat .dockerignore || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ../infra/docker/api.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myweb-docker-api:latest

      - name: Build and push WEB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/web.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myweb-docker-web:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/myweb-docker
            docker compose -f docker-compose.deploy.yml pull
            docker compose -f docker-compose.deploy.yml down
            docker compose -f docker-compose.deploy.yml up -d
            docker ps
